* Extensions

  Some of the greatest features of Emacs come from extensions.

** Repositories

   Initialize the list of repositories we subscribe to.

   #+BEGIN_SRC emacs-lisp
   (setq package-archives '())
   #+END_SRC

*** GNU

   The Free Software Foundation's official Emacs repository.

   #+BEGIN_SRC emacs-lisp
   (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
   #+END_SRC

*** ELPA

   The original Emacs repository.

   #+BEGIN_SRC emacs-lisp
   (add-to-list 'package-archives '("elpa" . "http://tromey.com/elpa/"))
   #+END_SRC

*** MELPA

   This repository contains less-stable user-contributed extensions, so we put it before Marmalade so the latter takes precedence.

   #+BEGIN_SRC emacs-lisp
   (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
   #+END_SRC

*** Marmalade

   This repository contains stable user-contributed extensions.

   #+BEGIN_SRC emacs-lisp
   (add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
   #+END_SRC

*** Org-mode

   This repository is dedicated to Org-mode.

   #+BEGIN_SRC emacs-lisp
   (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
   #+END_SRC

** Bootstrap

   Install or initialize el-get, a great package manager.

   #+BEGIN_SRC emacs-lisp
   (add-to-list 'load-path "~/.emacs.d/el-get/el-get")
   (unless (require 'el-get nil t)
     (with-current-buffer
         (url-retrieve-synchronously "https://raw.github.com/dimitri/el-get/master/el-get-install.el")
       (let (el-get-master-branch el-get-install-skip-emacswiki-recipes)
         (end-of-buffer)
         (eval-print-last-sexp))))
   #+END_SRC

** Packages

   These are the packages that we'd like to have installed, with some configuration specified.

   #+BEGIN_SRC emacs-lisp
   (setq el-get-sources
         '((:name key-chord
            :after (key-chord-mode 1))
           (:name ace-jump-mode
            :after (key-chord-define-global "uh" 'ace-jump-mode))
           (:name browse-kill-ring
            :after (global-set-key (kbd "C-M-y") 'browse-kill-ring))
           (:name color-theme-solarized
            :after (load-theme 'solarized-dark t))
           (:name expand-region
            :after (global-set-key (kbd "S-SPC") 'er/expand-region))
           (:name helm
            :after (progn
                    (global-set-key (kbd "M-x") 'helm-M-x)
                    (global-set-key (kbd "C-x b") 'helm-buffers-list)
                    (global-set-key (kbd "C-x f") 'helm-find-files)))
           (:name magit
            :type elpa
            :after (global-set-key (kbd "C-M-v") 'magit-status))
           (:name undo-tree
            :after (progn
                    (require 'undo-tree)
                    (global-set-key (kbd "C-M-z") 'undo-tree-visualize)))))
   #+END_SRC

   Combine implicitly and explicitly sourced packages.

   #+BEGIN_SRC emacs-lisp
   (setq mak/packages
         (append
          '(command-frequency
            dired+
            el-get
            erc
            flymake-point
            gist
            markdown-mode
            paredit
            twittering-mode
            yasnippet)
          (mapcar 'el-get-source-name el-get-sources)))
   #+END_SRC

** Garbage Collection

   Ensure that no packages are installed that we no longer want.

   #+BEGIN_SRC emacs-lisp
   (el-get-cleanup mak/packages)
   #+END_SRC

** Install or Update

   Download the newest version of the packages we subscribe to, and initialize them.

   #+BEGIN_SRC emacs-lisp
   (el-get 'sync mak/packages)
   #+END_SRC
