* Extensions

  Some of the greatest features of Emacs come from extensions.

** Repositories

   Initialize the list of repositories we subscribe to.

   #+begin_src emacs-lisp
   (setq package-archives '())
   #+end_src

*** GNU

   The Free Software Foundation's official Emacs repository.

   #+begin_src emacs-lisp
   (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
   #+end_src

*** ELPA

   The original Emacs repository.

   #+begin_src emacs-lisp
   (add-to-list 'package-archives '("elpa" . "http://tromey.com/elpa/"))
   (setq package-archives (append package-archives '(
     ())))
   #+end_src

*** MELPA

   This repository contains less-stable user-contributed extensions, so we put it before Marmalade so the latter takes precedence.

   #+begin_src emacs-lisp
   (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
   #+end_src

*** Marmalade

   This repository contains stable user-contributed extensions.

   #+begin_src emacs-lisp
   (add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
   #+end_src

*** Org-mode

   This repository is dedicated to Org-mode.

   #+begin_src emacs-lisp
   (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
   #+end_src

** Bootstrap

   Install or initialize el-get, a great package manager.

   #+begin_src emacs-lisp
   (add-to-list 'load-path "~/.emacs.d/el-get/el-get")
   (unless (require 'el-get nil t)
     (with-current-buffer
         (url-retrieve-synchronously "https://raw.github.com/dimitri/el-get/master/el-get-install.el")
       (let (el-get-master-branch el-get-install-skip-emacswiki-recipes)
         (end-of-buffer)
         (eval-print-last-sexp))))
   #+end_src

** Packages

   These are the packages that we'd like to have installed, with some configuration specified.

   #+begin_src emacs-lisp
     (setq el-get-sources
           '((:name ace-jump-mode)
             (:name browse-kill-ring
              :after (global-set-key (kbd "C-M-y") 'browse-kill-ring))
             (:name expand-region
              :after (global-set-key (kbd "S-SPC") 'er/expand-region))
             (:name key-chord
              :after (progn
                      (key-chord-mode 1)
                      (key-chord-define-global "uh" 'ace-jump-mode)))
             (:name magit)
             (:name undo-tree
              :type elpa
              :after (progn
                      (require 'undo-tree)
                      (global-set-key (kbd "C-M-z") 'undo-tree-visualize)))))
   #+end_src

   Combine implicitly and explicitly sourced packages.

   #+begin_src emacs-lisp
   (setq mak/packages
         (append
          '(color-theme-solarized
            command-frequency
            dired+
            el-get
            erc
            expand-region
            flymake-point
            gist
            helm
            markdown-mode
            paredit
            twittering-mode
            yasnippet)
          (mapcar 'el-get-source-name el-get-sources)))
   #+end_src

** Garbage Collection

   Ensure that no packages are installed that we no longer want.

   #+begin_src emacs-lisp
   (el-get-cleanup mak/packages)
   #+end_src

** Install or Update

   Download the newest version of the packages we subscribe to, and initialize them.

   #+begin_src emacs-lisp
   (el-get 'sync mak/packages)
   #+end_src
